
close = cv2.imread('templates/close.png')
closegift = cv2.imread('templates/closegift.png')
isgift = cv2.imread('templates/isgift.png')
addfriend = cv2.imread('templates/addfriend.png')
opengift = cv2.imread('templates/open.png')
reroll_receive = cv2.imread('templates/reroll_receive.png')
reroll_send = cv2.imread('templates/reroll_send.png')
refresh_receive = cv2.imread('templates/refresh_receive.png')
refresh_send = cv2.imread('templates/refresh_send.png')
sendgift = cv2.imread('templates/sendgift.png')
firstgift = cv2.imread('templates/firstgift.png')
pressend = cv2.imread('templates/send.png')
quitgift = cv2.imread('templates/quitgift.png')
bonus = cv2.imread('templates/bonus.png')